name: JSONKit
options:
  bundleIdPrefix: com.joblogiclibrary
  deploymentTarget:
    iOS: 13.0
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
  xcodeVersion: "14.0"

targets:
  JSONKit:
    type: framework
    platform: iOS
    sources:
      - path: Sources/JSONKit
        publicHeaders:
          - include/JSONKit.h
          - include/NSString+JSONKit.h
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.joblogiclibrary.JSONKit
        PRODUCT_NAME: JSONKit
        MACH_O_TYPE: staticlib
        SKIP_INSTALL: NO
        BUILD_LIBRARY_FOR_DISTRIBUTION: YES
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundlePackageType: FMWK
        INFOPLIST_KEY_NSHumanReadableCopyright: Copyright © 2024 Joblogic. All rights reserved.
        INFOPLIST_KEY_CFBundleShortVersionString: 1.0.0
        INFOPLIST_KEY_CFBundleVersion: 1
        SWIFT_VERSION: 5.0
        SWIFT_OPTIMIZATION_LEVEL: -Onone
        DEFINES_MODULE: YES
        CLANG_ENABLE_MODULES: YES
        MODULEMAP_FILE: Sources/JSONKit/include/module.modulemap
        PUBLIC_HEADERS_FOLDER_PATH: Headers
        PRIVATE_HEADERS_FOLDER_PATH: PrivateHeaders
        HEADER_SEARCH_PATHS: Sources/JSONKit/include
        USER_HEADER_SEARCH_PATHS: Sources/JSONKit/include
        ALWAYS_SEARCH_USER_PATHS: YES
        PUBLIC_HEADERS_PATHS: Sources/JSONKit/include
        COPY_HEADERS_RUN_PHASE_PRODUCTS: YES
        COPY_HEADERS_RUN_PHASE_PUBLIC: YES
        COPY_HEADERS_RUN_PHASE_PRIVATE: YES 